import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header, Footer,  } from "@/app/components/index"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://port2-fbn.netlify.app/"),
  title: "PfFabian",
  description: "Generated by create next app",
  keywords: "Next.js, SEO, proyecto web, desarrollo web",
  authors: [
    {
      name: "Fabian", // Nombre del autor
      url: "https://github.com/Fabian1803", // URL relacionada con el autor o empresa
    },
  ],
  openGraph: {
    title: "Mi Aplicación Next.js",
    description: "Explora nuestra aplicación web desarrollada con Next.js, una solución moderna para tus necesidades.",
    url: "https://tusitio.com",
    images: "https://tusitio.com/imagen-para-compartir.jpg",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Mi Aplicación Next.js",
    description: "Una aplicación web moderna desarrollada con Next.js.",
    images: ["https://tusitio.com/imagen-para-twitter.jpg"],
  },
  viewport: "width=device-width, initial-scale=1.0",
  themeColor: "var(--quaternary)",  
  other: {
    google: 'notranslate',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        id='home' 
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
